// Code generated by "stringer -type=ExportStatus"; DO NOT EDIT.

package vault

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExportStatusUnknown-0]
	_ = x[ExportStatusUnspecified-1]
	_ = x[ExportStatusCompleted-2]
	_ = x[ExportStatusFailed-3]
	_ = x[ExportStatusInProgress-4]
}

const _ExportStatus_name = "ExportStatusUnknownExportStatusUnspecifiedExportStatusCompletedExportStatusFailedExportStatusInProgress"

var _ExportStatus_index = [...]uint8{0, 19, 42, 63, 81, 103}

func (i ExportStatus) String() string {
	if i < 0 || i >= ExportStatus(len(_ExportStatus_index)-1) {
		return "ExportStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExportStatus_name[_ExportStatus_index[i]:_ExportStatus_index[i+1]]
}
