// Code generated by "stringer -type=MatterState"; DO NOT EDIT.

package vault

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MatterStateUnknown-0]
	_ = x[MatterStateUnspecified-1]
	_ = x[MatterStateOpen-2]
	_ = x[MatterStateClosed-3]
	_ = x[MatterStateDeleted-4]
}

const _MatterState_name = "MatterStateUnknownMatterStateUnspecifiedMatterStateOpenMatterStateClosedMatterStateDeleted"

var _MatterState_index = [...]uint8{0, 18, 40, 55, 72, 90}

func (i MatterState) String() string {
	if i < 0 || i >= MatterState(len(_MatterState_index)-1) {
		return "MatterState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatterState_name[_MatterState_index[i]:_MatterState_index[i+1]]
}
